---
- name: add user and generate key, print public key
  hosts: All
  user: root
                                    # become: yes
                                    #become_method: sudo

  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Remove the user 'ansible'
    user: 
      name: ansible 
      state: absent 
      remove: yes

  - name: Add the user 'ansible'
    user:
      name: ansible
      create_home: true
      shell: /bin/bash
      group: wheel
      uid: 2222
      generate_ssh_key: true
      ssh_key_bits: 2048
      state: present 
    register: new_user_key
  - debug: msg="{{ new_user_key.ssh_public_key }}"

  - name: Changing the public_keys on remote system
    lineinfile:
      dest: /root/.ssh/authorized_keys
      line: "{{ new_user_key.ssh_public_key }}"
      #insertafter: "{{ new_user_key.ssh_public_key }}"
    become: yes
    delegate_to: "{{ IP }}"
#    src: "~/home/ansible/.ssh/id_rsa.pub"
#      dest: ".ssh/authorized_keys"
#      mode: push
#     delegate_to: centos@35.176.186.173
#     register: syncfile
#  - name: cp the key
#    shell: scp ~/home/ansible/.ssh/id_rsa.pub centos@54.229.81.184:/tmp3