---
- name: name job
  hosts: Centos
  tasks:
  - name: Creating groups
    group: name="{{item.wheel}}" gid="{{item.gid | default(omit)}}"
    with_items: "{{groups_to_create}}"
    tags: ['users','groups','configuration']     
  
  tasks:
  - hosts: Centos
    name: root 
    users: sudo
    become: yes
    become_method: sudo                     
    connection: ssh
    gather_facts: no
    tasks:
    - name: Add me                # Create user to remote system 
      users: 
        name : bob
        state: present
        comment: System engineering


- name: Add authorized_keys for users      
  authorized_key:
    users: "{{ item.0.me }}"
    key:  "{{ item.1 }}"
  with_subelements:
    - "{{ users_add_users }}"
    - ssh_keys
    - skip_missing: true