---
- name: unziping wordpress 
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Download foo.conf
      get_url:
        url: http://example.com/path/file.conf
        dest: /etc/foo.conf
        mode: 0440

