---
- name: unziping wordpress 
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Download foo.conf
      get_url:
        url: https://wordpress.org/latest.tar.gz) 
        dest: /tmp/wordpress*
      

